#!/usr/bin/env bash

case x"$@" in


  x"(laptophp): Only laptop screen monitor")
    xrandr --output eDP-1 --auto 
    xrandr --output HDMI-1 --off
	xrdb ~/.Xresources
    exit 0
    ;;

  x"(laptophp): Only external monitor")
    xrandr --output eDP-1 --off
    xrandr --output HDMI-1 --auto
	xrdb ~/.Xresources_extmonitor
    exit 0
    ;;

  x"i3-resurrect save all workspaces")
    i3-resurrect save -w 1
    i3-resurrect save -w 2
    i3-resurrect save -w 3
    i3-resurrect save -w 4
    i3-resurrect save -w 5
    i3-resurrect save -w 6
    i3-resurrect save -w 7
    i3-resurrect save -w 8
    i3-resurrect save -w 9
    i3-resurrect save -w 10
    exit 0
    ;;

  x"i3-resurrect restore all workspaces")
    i3-resurrect restore -w 1
    i3-resurrect restore -w 2
    i3-resurrect restore -w 3
    i3-resurrect restore -w 4
    i3-resurrect restore -w 5
    i3-resurrect restore -w 6
    i3-resurrect restore -w 7
    i3-resurrect restore -w 8
    i3-resurrect restore -w 9
    i3-resurrect restore -w 10
    exit 0
    ;;

  *)
    # Echo here the available options
    echo "(laptophp): Only laptop screen monitor"
    echo "(laptophp): Only external monitor"
    echo "i3-resurrect save all workspaces"
    echo "i3-resurrect restore all workspaces"
    ;;
    
esac

